image: "rust:latest"

stages:
    - fmt
    - test
    - deploy


deploy_script:
    stage: deploy
    script: 
        - echo "I'm mock deploying something!"

cargo_fmt:
    stage: fmt
    before_script:
        - rustup component add rustfmt
    script:
        - cargo fmt --all -- --check


test:cargo:
    stage: test  
    script:
        - rustc --version && cargo --version  # Print version info for debugging
        - cargo test --workspace --verbose
